=== neoradar-project/packager/schemas/input_manifest.schema.json
{
  "$ref": "#/definitions/InputManifest",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "InputManifest": {
      "additionalProperties": false,
      "properties": {
        "aliasPath": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "esePath": {
          "type": "string"
        },
        "icaoAircraftPath": {
          "type": "string"
        },
        "icaoAirlinesPath": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "loginProfilesPath": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "namespace": {
          "type": "string"
        },
        "outputDir": {
          "type": "string"
        },
        "recatDefinitionPath": {
          "type": "string"
        },
        "sctPath": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "name",
        "description",
        "namespace",
        "sctPath",
        "esePath",
        "loginProfilesPath",
        "icaoAircraftPath",
        "icaoAirlinesPath",
        "aliasPath",
        "outputDir"
      ],
      "type": "object"
    }
  }
}

=== neoradar-project/packager/input.json
{
    "id": "LFXX_AIRAC_2412_1",
    "name": "LFXX - AIRAC 2412 Rev 1",
    "description": "LFXX 2412 with LFMN AVISO v2",
    "namespace": "lfxx",
    "sctPath": "src/data/lfxx/lfxx.sct",
    "esePath": "src/data/lfxx/lfxx.ese",
    "loginProfilesPath": "src/data/lfxx/LoginProfiles.txt",
    "icaoAircraftPath": "src/data/lfxx/ICAO_Aircraft.txt",
    "icaoAirlinesPath": "src/data/lfxx/ICAO_Airlines.txt",
    "recatDefinitionPath": "src/data/lfxx/recat-eu.json",
    "aliasPath": "src/data/lfxx/alias.txt",
    "outputDir": "build/"
}
